config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root "groups#index"
  resources :users,  except: [:show, :create]
  resources :groups, except: [:show, :destroy] do
    resources :messages, only: [:index, :create]
    namespace :api do
      resources :messages, only: :index, defaults: { format: 'json' }
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/group.rb
class Group < ApplicationRecord
  has_many :users, through: :group_users
  has_many :group_users
  has_many :messages
  validates :name, presence: true, uniqueness: true

  def show_last_message
    if (last_message = messages.last).present?
      if last_message.body?
        last_message.body
      else
        '画像が投稿されています'
      end
    else
      'まだメッセージはありません。'
    end
  end
end

app/models/group_user.rb
class GroupUser < ApplicationRecord
  belongs_to :user
  belongs_to :group
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :user
  belongs_to :group
  validates :body, presence: true, unless: :image?
  mount_uploader :image, ImageUploader
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :groups, through: :group_users
  has_many :group_users
  has_many :messages
end

app/controllers/api/messages_controller.rb
class Api::MessagesController < ApplicationController
  def index
    group = Group.find(params[:group_id])
    last_message_id = params[:id].to_i
    @messages = group.messages.includes(:user).where("id > ?", last_message_id)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected
  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:nickname])
  end
end 

app/controllers/groups_controller.rb
class GroupsController < ApplicationController

  def index
  end
  

  def new
    @group = Group.new
    @group.users << current_user
  end

  def create
  @group = Group.new(group_params)
    if @group.save
      redirect_to root_path, notice: 'グループを作成しました'
    else
      render :new
    end
  end

  def edit
    @group = Group.find(params[:id])
  end

  def update
    @group = Group.find(params[:id])
    if @group.update(group_params)
    redirect_to group_messages_path(@group.id), notice: 'グループを編集しました'
  else
    render :edit
  end
end


  private
  def group_params
    params.require(:group).permit(:name, user_ids: [])
  end

end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  
  def index
    @message = Message.new
    @group = Group.find(params[:group_id])
    @messages = @group.messages.includes(:user)
  end

  def create
    @group = Group.find(params[:group_id])
    @message = @group.messages.new(message_params)
    if @message.save
      respond_to do |format|
        format.json
      end
    else
      @messages = @group.messages.includes(:user)
      flash.now[:alert] = 'メッセージを入力してください。'
      render :index
    end
  end

  private
  def message_params
    params.require(:message).permit(:body, :image).merge(user_id: current_user.id)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController


  def index
    return nil if params[:keyword] == ""
    @users = User.where(['nickname LIKE ?', "%#{params[:keyword]}%"] ).where.not(id: current_user.id).limit(10)
    respond_to do |format|
      format.html
      format.json
    end
  end


  def new
  end


  def edit
  end

  def delete
  end
  

  def update
    if current_user.update(user_params)
      redirect_to root_path
    else
      render :edit
    end
  end

  private

  def user_params
    params.require(:user).permit(:name, :email)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/groups/_form.html.haml
= form_for group do |f|
  - if group.errors.any?
    .chat-group-form__errors
      %h2= "#{group.errors.full_messages.count}件のエラーが発生しました。"
      %ul
        - group.errors.full_messages.each do |message|
          %li= message
  .chat-group-form__field
    .chat-group-form__field--left
      = f.label :name, class: 'chat-group-form__label'
    .chat-group-form__field--right
      = f.text_field :name, class: 'chat__group_name chat-group-form__input', placeholder: 'グループ名を入力してください'
  .chat-group-form__field
    .chat-group-form__field--left
      %label.chat-group-form__label{:for => "chat_group_チャットメンバーを追加"} チャットメンバーを追加
    .chat-group-form__field--right
      .chat-group-form__search.clearfix
        %input#user-search-field.chat-group-form__input{:placeholder => "追加したいユーザー名を入力してください", :type => "text"}/
      #user-search-result

  .chat-group-form__field.clearfix
    .chat-group-form__field--left
      %label.chat-group-form__label{:for => "chat_group_チャットメンバー"} チャットメンバー
    .chat-group-form__field--right
      #chat-group-users.js-add-user
        .chat-group-user.clearfix.js-chat-member
          %input{name: "group[user_ids][]", type: "hidden", value: current_user.id}
          %p.chat-group-user__name= current_user.nickname

        - group.users.each do |user|
          - if current_user.nickname != user.nickname
            .chat-group-user.clearfix.js-chat-member
              %input{name: "group[user_ids][]", type: "hidden", value: user.id}
              %p.chat-group-user__name
                = user.nickname
              %a.user-search-remove.chat-group-user__btn.chat-group-user__btn--remove.js-remove-btn
                削除

  .chat-group-form__field.clearfix
    .chat-group-form__field--left
    .chat-group-form__field--right
      = f.submit class: 'chat-group-form__action-btn'

app/views/groups/edit.html.haml
.chat-group-form
  %h1 チャットグループ編集
  = render partial: 'form', locals: { group: @group }

app/views/groups/index.html.haml
.wrapper
  = render 'shared/side_bar'

app/views/groups/new.html.haml
.chat-group-form
  %h1 新規チャットグループ
  = render partial: 'form', locals: { group: @group }

app/views/layouts/_notifications.html.haml
.notification
  - flash.each do |key, value|
    =content_tag :div, value, class: key

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title ChatSpace
    = csrf_meta_tags
    = stylesheet_link_tag    'application', media: 'all'
    = javascript_include_tag 'application'
  %body
    = render 'layouts/notifications'
    = yield

app/views/messages/_message.html.haml
.chat-main__message-list__content{data: {message: {id: message.id}}}
  .chat-main__message-list__content__user-area
    .chat-main__message-list__content__user-area--name
      = message.user.nickname
    .chat-main__message-list__content__user-area--date
      = message.created_at.strftime("%Y/%m/%d  %H:%M")
  .chat-main__message-list__content__message-area
    - if message.body.present?
      .chat-main__message-list__content__message-area--text
        = message.body
    = image_tag message.image.url, class: "message_image" if message.image.present?

app/views/messages/index.html.haml
.wrapper
  = render "shared/side_bar"
  = render "shared/main_chat"

app/views/shared/_main_chat.html.haml
.chat-main
  .chat-main__group-info
    .chat-main__group-info__left
      .chat-main__group-info__left--group-name
        = @group.name
      .chat-main__group-info__left--menbers-list
        menber: 
        - @group.users.each do |user|
          .chat-main__group-info__left--menbers-list--name
            = user.nickname
    .chat-main__group-info__right
      = link_to edit_group_path(@group.id), class: "chat-main__group-info__right--text" do
        Edit

  .chat-main__message-list
    = render @messages

  = form_for [@group, @message], html: { class: "form_reset" } do |f|
    .chat-main__message-form
      .chat-main__message-form__box
        = f.text_field :body, placeholder: 'type a message', class: "chat-main__message-form__box__text"
        .chat-main__message-form__box--image-btn
          = f.label :image do
            = icon('fas', 'image', class: "chat-main__message-form__box--image-btn")
            = f.file_field :image, class: 'hidden'
      = f.submit 'Send', class: "chat-main__message-form--send-btn"

app/views/shared/_side_bar.html.haml
.side-ber
  .side-ber__user-name
    .side-ber__user-name__box
      .side-ber__user-name__box--text
        = current_user.nickname
      .side-ber__user-name__box--icon-area
        = link_to new_group_path, class: "side-ber__user-name__box--icon-area--icon" do
          = icon('fas', 'edit')
        = link_to edit_user_path(current_user), class: "side-ber__user-name__box--icon-area--icon" do
          = icon('fas', 'cog')
  .side-ber__group-list
    - current_user.groups.each do |group|
      .side-ber__group-list__box
        = link_to group_messages_path(group.id), class: "none" do
          .side-ber__group-list__box__group-name
            = group.name
          .side-ber__group-list__box__new-message
            = group.show_last_message

app/views/users/edit.html.haml
#account-page.account-page
  .account-page__inner.clearfix
    .account-page__inner--left.account-page__header
      %h2 Edit Account
      %h5 アカウントの編集
      = link_to "ログアウト", destroy_user_session_path, method: :delete, class: 'btn'
      = link_to "トップページに戻る", :back, class: 'btn'
    .account-page__inner--right.user-form
      = form_for(current_user) do |f|
        .field
          .field-label
            = f.label :nickname
          .field-input
            = f.text_field :nickname, autofocus: true
        .field
          .field-label
            = f.label :email
          .field-input
            = f.email_field :email
        .actions
          = f.submit "Update", class: 'btn'